"""create users and auth_identities

Revision ID: 459ce05db2a9
Revises: 
Create Date: 2025-10-01 16:18:20.315774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '459ce05db2a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_users_email_not_null', 'users', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_table('auth_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('email', 'username', 'room', 'phone', 'sso', name='providerenum'), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('identifier_normalized', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'identifier_normalized', name='uq_identity_provider_identifier')
    )
    op.create_index(op.f('ix_auth_identities_identifier_normalized'), 'auth_identities', ['identifier_normalized'], unique=False)
    op.create_index(op.f('ix_auth_identities_provider'), 'auth_identities', ['provider'], unique=False)
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_index(op.f('ix_auth_identities_provider'), table_name='auth_identities')
    op.drop_index(op.f('ix_auth_identities_identifier_normalized'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index('uq_users_email_not_null', table_name='users', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_table('users')
    # ### end Alembic commands ###
